services:
  postgres:
    image: postgres:16-alpine
    container_name: epos-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: epos
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
